# ==============================================================================
# run-flux-validate-repo
#   * Repo-Based
#   * Recursive
#   * Executes if .yaml files are modified
# ==============================================================================
-   id: run-flux-validate-repo
    name: 'run-flux-validate-repo'
    entry: run-flux-validate-repo.sh
    files: '(\.yaml$)'
    language: 'script'
    description: "Run 'validate.sh' in repo root folder"
    pass_filenames: false
    require_serial: true
-   id: run-flux-validate
    name: 'run-flux-validate'
    entry: run-flux-validate.sh
    files: '(\.yaml$)'
    language: 'script'
    description: "Run 'validate.sh' in each changed folder"
    pass_filenames: true
    require_serial: true
